# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    prefer-ip-address: true
    ip-address: 172.16.18.217
  client:
    serviceUrl:
      defaultZone: http://user:password@172.16.18.217:8060/eureka
# configure Client Name
spring:
  application:
    name: account-client
  # H2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  # Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
